CREATE TABLE "EXN1"."CALL_TYPE"
(
    "EVENT_TYPE_ID"     VARCHAR2(5),
    "SUB_EVENT_TYPE_ID" VARCHAR2(2),
    "MODIFIER"          VARCHAR2(5),
    "CALL_TYPE"         VARCHAR2(2),
    "CHRG_TYPE"         VARCHAR2(1),
    "COMPANY_NAME"      VARCHAR2(3)
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."CALL_TYPE_KEY_IX" ON "EXN1"."CALL_TYPE" ("EVENT_TYPE_ID", "SUB_EVENT_TYPE_ID", "MODIFIER") TABLESPACE "CCARE_FRAUD_ALERT";
