CREATE TABLE "EXN1"."IR_ONETARIFF_RATE"
(
    "PMN_CODE"              VARCHAR2(10) NOT NULL,
    "COUNTRYCODE"           VARCHAR2(10) NOT NULL,
    "MTC_CHR"               NUMBER(18,0),
    "GPRS_CHR"              NUMBER(18,0),
    "SMST_CHR"              NUMBER(18,0),
    "SMSO_CHR"              NUMBER(18,0),
    "MOC_CHR_TO_THAILAND"   NUMBER(18,0),
    "MOC_CHR_LOCAL"         NUMBER(18,0),
    "MOC_CHR_INTER"         NUMBER(18,0),
    "GMT_OFFSET"            NUMBER(18,2),
    "GPRS_MIN"              NUMBER(18,2),
    "GPRS_ROUND"            NUMBER(18,2),
    --"Region_Code"         VARCHAR2(10),
    --"Country_Name"        VARCHAR2(200),
    --"Operator_Name"       VARCHAR2(200),
    "CHARGE_TYPE"           VARCHAR2(1) NOT NULL,
    "IDD_ACCESS_CODE"       VARCHAR2(200),
    "ROAMINGAREANUMBER"     VARCHAR2(100)
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."IR_ONETARIFF_RATE_KEY_IX1" ON "EXN1"."IR_ONETARIFF_RATE" ("PMN_CODE", "CHARGE_TYPE") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."IR_ONETARIFF_RATE_KEY_IX2" ON "EXN1"."IR_ONETARIFF_RATE" ("COUNTRYCODE") TABLESPACE "CCARE_FRAUD_ALERT";
