CREATE TABLE "EXN1"."IR_RISK_BNUMBER"
(
    "PATTERNID"     NUMBER(*,0)  NOT NULL,
    "BNUMBER"       VARCHAR2(50) NOT NULL,
    "UPDATEDATE"    DATE,
    "STATUS"        VARCHAR2(1),
    "USERFILENAME"  VARCHAR2(100),
    "USERUPLOAD"    VARCHAR2(10)
) TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."IR_RISK_BNUMBER_KEY_IX1" ON "EXN1"."IR_RISK_BNUMBER" ("PATTERNID", "BNUMBER") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE UNIQUE INDEX "EXN1"."IR_RISK_BNUMBER_KEY_IX2" ON "EXN1"."IR_RISK_BNUMBER" ("BNUMBER") TABLESPACE "CCARE_FRAUD_ALERT";
CREATE INDEX "EXN1"."IR_RISK_BNUMBER_KEY_IX3" ON "EXN1"."IR_RISK_BNUMBER" ("STATUS") TABLESPACE "CCARE_FRAUD_ALERT";

CREATE SEQUENCE "EXN1"."RISK_BNO_PAT_SEQ"
    MINVALUE     1
    START WITH   1
    INCREMENT BY 1
    CACHE        20;
